### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by rayenmessaoudi** [88d52bdba0366127fffca9dfa93895/cuckoomx#2]
Hi,
i have 2 questions :
1 - why cuckoomx can only parse exe files ?
2 - cuckoomx can't check periodically for new coming messages ?

also i need to help to solve these errors 
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jhon/Desktop/cuckoomx/lib/cuckoomx/core/offside.py", line 46, in offside
    if mail.analyze() is False:
  File "/home/jhon/Desktop/cuckoomx/lib/cuckoomx/core/mail.py", line 215, in analyze
    if self.process_attachments(self.attachments) is False:
  File "/home/jhon/Desktop/cuckoomx/lib/cuckoomx/core/mail.py", line 148, in process_attachments
    task_id = request.create_file(filename, payload)
  File "/home/jhon/Desktop/cuckoomx/lib/cuckoomx/core/request.py", line 93, in create_file
    task_id = response.json()["task_ids"]
KeyError: 'task_ids'

**Comment by 88d52bdba0366127fffca9dfa93895** [comment]
Hi @rayenmessaoudi, this is my very old project but nice to see it can help you,

1. In my memory, it could run with other extensions, you can see [here](https://github.com/88d52bdba0366127fffca9dfa93895/cuckoomx/blob/master/lib/cuckoomx/core/mail.py#L192)
2. Yes, it can't. Actually you can re-run it, I didn't finish it before I drop this project.

Your error looks like it has a strange behavior when requests an analysis for an attachment, [ref](https://github.com/88d52bdba0366127fffca9dfa93895/cuckoomx/blob/master/lib/cuckoomx/core/request.py#L80)

Hope that could help you, regards.

**Comment by rayenmessaoudi** [comment]
Problem solved Thanks :)

**Comment by 88d52bdba0366127fffca9dfa93895** [comment]
NP
